### PR TITLE
Release cling 0.9

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
AAARRRG, cling started patching LLVM again.
This makes me want to shoot myself.

**Comment by vgvassilev** [comment]
In theory we can compile without patching llvm if we could modify the header file in question -- the patch requires to make a data member from `private` to `protected`.

This PR also solves a broken ubuntu package not sure if helps in that case https://github.com/root-project/root/pull/8766

**Comment by SylvainCorlay** [comment]
> In theory we can compile without patching llvm if we could modify the header file in question -- the patch requires to make a data member from private to protected.
>
> This PR also solves a broken ubuntu package not sure if helps in that case root-project/root#8766

Thanks, I saw the private -> protected thing that could solve the first error without making the build binary incompatible, but I was unsure about other changes, so I have rebuilt the whole stack.

**Comment by SylvainCorlay** [comment]
**Linux failure:**

```
CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**OS X Failure**

```
+ cling '2+3; 0'
cling::IncrementalExecutor: unable to find target:
Unable to find target for this triple (no targets are registered)0  cling                    0x000000010d957606 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 54
1  cling                    0x000000010d956676 llvm::sys::RunSignalHandlers() + 198
2  cling                    0x000000010d957c86 SignalHandler(int) + 358
3  libsystem_platform.dylib 0x00007fff73b0f5fd _sigtramp + 29
4  libsystem_platform.dylib 0x0000000000000001 _sigtramp + 18446603338575186465
5  cling                    0x000000010d8223ac llvm::DataLayout::operator=(llvm::DataLayout const&) + 44
6  cling                    0x000000010d82758b cling::IncrementalJIT::IncrementalJIT(cling::IncrementalExecutor&, std::__1::unique_ptr<llvm::TargetMachine, std::__1::default_delete<llvm::TargetMachine> >, std::__1::function<void (unsigned long long, std::__1::unique_ptr<llvm::Module, std::__1::default_delete<llvm::Module> >)>) + 235
7  cling                    0x000000010d822baa cling::IncrementalExecutor::IncrementalExecutor(clang::DiagnosticsEngine&, clang::CompilerInstance const&) + 1018
8  cling                    0x000000010d835c05 cling::Interpreter::Interpreter(int, char const* const*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension> > > const&, bool, cling::Interpreter const*) + 2213
9  cling                    0x000000010d784fa8 main + 184
10 libdyld.dylib            0x00007fff73912cc9 start + 1
Stack dump:
0.	Program arguments: cling 2+3; 0 
/Users/runner/miniforge3/conda-bld/cling_1632121430925/test_tmp/run_test.sh: line 8: 33595 Segmentation fault: 11  cling '2+3; 0'
```

**Comment by chrisburr** [comment]
For Linux, I think this was caused by a bug in the LLVM CMake config when dynamic libraries are built in addition to static libraries. IIRC the workaround was this: https://github.com/conda-forge/root-feedstock/blob/2e557c73cb0d97ee79175110692a21d9a6604e99/recipe/build.sh#L128-L129

**Comment by SylvainCorlay** [comment]
Thanks @chrisburr.

I hope this does not require me to rebuild clangdev another time. This whole thing has been a nightmare.

**Comment by SylvainCorlay** [comment]
OK, it does not seem to strike it.

**Comment by vgvassilev** [comment]
Can you run somehow in verbose mode: eg `ninja -v`? I'd like to see the link command for cling. Can you also show how the clang package is compiled?

**Pull request closed without merging**
